/// Generated by Home Manager.

// user prefs


// accounts
user_pref("mail.account.account0.identities", "id0");
user_pref("mail.account.account0.server", "server0");
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.identity.id0.fullName", "Testi Mac Testface");
user_pref("mail.identity.id0.smtpServer", "smtp0");
user_pref("mail.identity.id0.useremail", "test@somewhere.org");
user_pref("mail.identity.id0.valid", true);
user_pref("mail.identity.id1.fullName", "Samy Mac Someface");
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.useremail", "some@somewhere.org");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.server.server0.hostname", "imap.somewhere.org");
user_pref("mail.server.server0.name", "prime");
user_pref("mail.server.server0.port", null);
user_pref("mail.server.server0.type", "imap");
user_pref("mail.server.server0.userName", "test-user");
user_pref("mail.server.server1.hostname", "imap.somewhere.org");
user_pref("mail.server.server1.name", "sec");
user_pref("mail.server.server1.port", null);
user_pref("mail.server.server1.type", "imap");
user_pref("mail.server.server1.userName", "some-user");
user_pref("mail.smtpserver.smtp0.authMethod", 3);
user_pref("mail.smtpserver.smtp0.description", "prime");
user_pref("mail.smtpserver.smtp0.hostname", "smpt.somewhere.org");
user_pref("mail.smtpserver.smtp0.port", null);
user_pref("mail.smtpserver.smtp0.try_ssl", 2);
user_pref("mail.smtpserver.smtp0.username", "test-user");
user_pref("mail.smtpserver.smtp1.authMethod", 3);
user_pref("mail.smtpserver.smtp1.description", "sec");
user_pref("mail.smtpserver.smtp1.hostname", "smpt.somewhere.org");
user_pref("mail.smtpserver.smtp1.port", null);
user_pref("mail.smtpserver.smtp1.try_ssl", 2);
user_pref("mail.smtpserver.smtp1.username", "some-user");

// extraPrefs


/// End of Home Manager generated Part.
